### ISSUE TITLE
Linux: Podcastmenü keine Emojis

### ISSUE THREAD

**Issue by fernsehmuell** [Ultraschall/ultraschall-installer#33]
Es werden keine Emojis angezeigt im Podcastmenü
Das tritt auf unter arch, ubuntu und NixOS. Also kein Problem einer bestimmten Distro. Ich habe es unter NixOS auch mit reaper 7.25 probiert. Gleiches Ergebnis.
Einfachste Lösung erstmal: die Datei reaper-menu.ini von Emojis befreien im Linux Installer build step. 
![Image](https://github.com/user-attachments/assets/8a39b6f0-626c-4f14-9445-aa328b7d7525)

**Comment by mespotine** [comment]
Done
